Fix the error handling

diff --git a/.github/actions/bundle_size_test/action.yml b/.github/actions/bundle_size_test/action.yml
--- a/.github/actions/bundle_size_test/action.yml
+++ b/.github/actions/bundle_size_test/action.yml
@@ -21,17 +21,16 @@ runs:
     run: |-
         json_string='${{ inputs.config }}'
 
-        # Parse the given json string and build the command to run
-        while read -r command; do
-          # Example of command: npx bundlesize -f "build/main.js" -s 10kB
-          eval $command
-        done < <(echo "$json_string" | jq -r 'to_entries[] | "npx bundlesize -f \"" + .key + "\" -s " + .value')
-
-        # Check the exit status of the jq command
-        if [ "${PIPESTATUS[0]}" -ne 0 ]; then
-          echo "Error: jq failed to parse the JSON input: $json_string" >&2
+        if ! echo "$json_string" | jq '.' > /dev/null 2>&1; then
+          echo "::error::Invalid JSON input provided: $json_string"
           exit 1
         fi
+
+        # Parse the given json string and build the command to run
+        echo "$json_string" | jq -r 'to_entries[] | "npx bundlesize -f \"" + .key + "\" -s " + .value' | while IFS= read -r command; do
+          echo "Executing: $command"
+          eval "$command"
+        done
     shell: bash
 
   - name: Report bundle sizes
