Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -158,6 +158,45 @@ commands:
               # that would prevent Lerna from publishing (Lerna gets this right).
               git diff --exit-code
 
+  generate_and_test_project:
+    description: 'Generate project'
+    steps:
+      - run:
+          name: Generate project
+          environment:
+            GENERATOR_PRESET: 'test-project'
+          command: |
+            node ./scripts/gtime.js generated_project_install \
+                node packages/pwa-kit-create-app/scripts/create-mobify-app-dev.js --outputDir /tmp/project
+            
+            cd /tmp/project
+            npm run prod:build
+      - run:
+          name: Generate hello-world project
+          environment:
+            GENERATOR_PRESET: 'hello-world-test-project'
+          command: |
+            node packages/pwa-kit-create-app/scripts/create-mobify-app-dev.js --outputDir /tmp/hello-world
+      - runtests:
+          cwd: /tmp/project
+      - smoketestscripts:
+          dir: /tmp/project
+      - run:
+          name: Count Generated Project Dependencies
+          environment:
+          command: |
+            MAX_PACKAGES="2250"
+            total=$(./scripts/count-dependencies.js /tmp/project)
+            echo "export TOTAL_PACKAGES=${total}" >> $BASH_ENV;
+            source $BASH_ENV
+
+            if [ "$total" -gt "$MAX_PACKAGES" ]; then
+                echo "Error: Found $TOTAL_PACKAGES installed packages (max $MAX_PACKAGES).";
+                exit 1;
+            else
+                echo "Found $TOTAL_PACKAGES installed packages (max $MAX_PACKAGES).";
+            fi
+
   early_return_for_forked_pull_requests:
     description: >-
       If this build is from a fork, stop executing the current job and return success.
@@ -270,41 +309,7 @@ jobs:
     steps:
       - checkout
       - setup
-      - run:
-          name: Generate project
-          environment:
-            GENERATOR_PRESET: 'test-project'
-          command: |
-            node ./scripts/gtime.js generated_project_install \
-                node packages/pwa-kit-create-app/scripts/create-mobify-app-dev.js --outputDir /tmp/project
-
-            cd /tmp/project
-            npm run prod:build
-      - run:
-          name: Generate hello-world project
-          environment:
-            GENERATOR_PRESET: 'hello-world-test-project'
-          command: |
-            node packages/pwa-kit-create-app/scripts/create-mobify-app-dev.js --outputDir /tmp/hello-world
-      - runtests:
-          cwd: /tmp/project
-      - smoketestscripts:
-          dir: /tmp/project
-      - run:
-          name: Count Generated Project Dependencies
-          environment:
-          command: |
-            MAX_PACKAGES="2250"
-            total=$(./scripts/count-dependencies.js /tmp/project)
-            echo "export TOTAL_PACKAGES=${total}" >> $BASH_ENV;
-            source $BASH_ENV
-
-            if [ "$total" -gt "$MAX_PACKAGES" ]; then
-                echo "Error: Found $TOTAL_PACKAGES installed packages (max $MAX_PACKAGES).";
-                exit 1;
-            else
-                echo "Found $TOTAL_PACKAGES installed packages (max $MAX_PACKAGES).";
-            fi
+      - generate_and_test_project
       - early_return_for_forked_pull_requests
       - slack/status:
           fail_only: true
@@ -351,6 +356,15 @@ jobs:
               cd /tmp/project
               npm run push -- --message "Generated PWA build ${CIRCLE_BUILD_NUM} on ${CIRCLE_BRANCH} (${CIRCLE_SHA1})" --target $target
             fi
+  generatedSFCCProjectTestWindows:
+    executor:
+      name: win/default
+      size: "large"
+      shell: bash.exe
+    steps:
+      - checkout
+      - setup_windows
+      - generate_and_test_project
 
 workflows:
   version: 2
