refactor

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,20 +11,10 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [windows-latest, ubuntu-latest]
         node: [14]
         npm: [6, 7, 8]
-        exclude:
-          - os: windows-latest
-            node: 14
-            npm: 7
-          - os: windows-latest
-            node: 14
-            npm: 8
-    runs-on: ${{ matrix.os }}
-    if: matrix.os == 'ubuntu-latest'
-      container:
-        image: node:14
+    runs-on: ubuntu-latest
+    container: node:14
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -41,12 +31,7 @@ jobs:
         shell: bash
 
       - name: Setup Ubuntu Machine
-        if: matrix.os == 'ubuntu-latest'
         uses: "./.github/actions/setup_ubuntu"
-
-      - name: Setup Windows Machine
-        if: matrix.os == 'windows-latest'
-        uses: "./.github/actions/setup_windows"
 
       - name: Install node dependencies with NPM version
         if: matrix.npm != 6
@@ -61,15 +46,15 @@ jobs:
         uses: "./.github/actions/runtests"
 
       - name: Run Lighthouse CI on the PWA
-        if: matrix.os == 'ubuntu-latest' && matrix.npm == 6
+        if: matrix.npm == 6
         uses: "./.github/actions/lighthouse-ci"
 
       - name: Smoke test scripts
-        if: matrix.os == 'ubuntu-latest' && matrix.npm == 6
+        if: matrix.npm == 6
         uses: "./.github/actions/smoketestscripts"
 
       - name: Create MRT credentials file
-        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && matrix.npm == 6 && matrix.os == 'ubuntu-latest'
+        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && matrix.npm == 6
         env:
           MOBIFY_CLIENT_USER: ${{ secrets.MOBIFY_CLIENT_USER }}
           MOBIFY_CLIENT_API_KEY: ${{ secrets.MOBIFY_CLIENT_API_KEY }}
@@ -79,7 +64,7 @@ jobs:
         shell: bash
 
       - name: Push Bundle to MRT
-        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && matrix.npm == 6 && matrix.os == 'ubuntu-latest'
+        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && matrix.npm == 6 
         #TODO: Change target 'test-env' to 'staging' and 'test-env-3' to 'commerce-sdk-react'
         run: |-
           if [[ $DEVELOP || $RELEASE ]]; then
@@ -99,7 +84,7 @@ jobs:
           fi
       #TODO: remove --dry-run from install command
       - name: Publish to NPM
-        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && matrix.npm == 6 && matrix.os == 'ubuntu-latest'
+        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && matrix.npm == 6
         env: 
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
         run: |-
@@ -118,7 +103,7 @@ jobs:
       #TODO: change github-actions to develop
       - name: Send GitHub Action data to Slack workflow (PWA Kit)
         id: slack
-        if: ${{ github.repository == 'SalesforceCommerceCloud/pwa-kit' && failure() && github.ref == 'refs/heads/github-actions' && matrix.npm == 6 && matrix.os == 'ubuntu-latest' }}
+        if: ${{ github.repository == 'SalesforceCommerceCloud/pwa-kit' && failure() && github.ref == 'refs/heads/github-actions' && matrix.npm == 6 }}
         uses: slackapi/slack-github-action@v1.23.0
         with:
           payload: |
@@ -127,17 +112,40 @@ jobs:
             }
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+  pwa-kit-windows:
+    strategy:
+        fail-fast: false
+        matrix:
+          node: [14]
+          npm: [6]
+    runs-on: windows-latest
+    steps:
+        - name: Checkout
+          uses: actions/checkout@v3
+
+        - name: Setup Node
+          uses: actions/setup-node@v3
+          with:
+            node-version: ${{ matrix.node }}
+            cache: npm
+
+        - name: Setup Windows Machine
+          uses: "./.github/actions/setup_windows"
+
+        - name: NPM version
+          run: npm --version
+
+        - name: Run tests
+          uses: "./.github/actions/runtests"
       
 
   generated:
     strategy:
       fail-fast: false
       matrix:
-        os: [windows-latest, ubuntu-latest]
         template: [test-project, retail-react-app-demo, express-minimal-test-project, typescript-minimal-test-project]
-    runs-on: ${{ matrix.os }}
-    container:
-      image: node:14
+    runs-on: ubuntu-latest
+    container: node:14
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -148,12 +156,7 @@ jobs:
           node-version: 14
 
       - name: Setup Ubuntu Machine
-        if: matrix.os == 'ubuntu-latest'
         uses: "./.github/actions/setup_ubuntu"
-
-      - name: Setup Windows Machine
-        if: matrix.os == 'windows-latest'
-        uses: "./.github/actions/setup_windows"
 
       - name: Generate ${{ matrix.template }} project
         run: |-
@@ -194,7 +197,7 @@ jobs:
         with:
           path: packages/pwa-kit-create-app/local-npm-repo/verdaccio.log
       - name: Send metrics to Datadog
-        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && (matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo') && matrix.os == 'ubuntu-latest'
+        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && (matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo')
         run : |
           # Add a dogrc so we can submit metrics to datadog
           printf "[Connection]\napikey = $DATADOG_API_KEY\nappkey =\n" > ~/.dogrc
@@ -203,7 +206,7 @@ jobs:
         env:
           DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
       - name: Create MRT credentials file
-        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && (matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo') && matrix.os == 'ubuntu-latest'
+        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && (matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo')
         env:
           MOBIFY_CLIENT_USER: ${{ secrets.MOBIFY_CLIENT_USER }}
           MOBIFY_CLIENT_API_KEY: ${{ secrets.MOBIFY_CLIENT_API_KEY }}
@@ -212,7 +215,7 @@ jobs:
           npm run save-credentials --prefix packages/template-retail-react-app -- --user "$MOBIFY_CLIENT_USER" --key "$MOBIFY_CLIENT_API_KEY"
         shell: bash
       - name: Push Bundle to MRT
-        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && (matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo') && matrix.os == 'ubuntu-latest'
+        if: github.repository == 'SalesforceCommerceCloud/pwa-kit' && (matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo')
         run: |
           if [[ $DEVELOP ]]; then
             target='generated-pwa'
@@ -229,7 +232,7 @@ jobs:
           fi
       - name: Send GitHub Action data to Slack workflow (Generated)
         id: slack
-        if: ${{ github.repository == 'SalesforceCommerceCloud/pwa-kit' && failure() && github.ref == 'refs/heads/github-actions' && (matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo') && matrix.os == 'ubuntu-latest' }}
+        if: ${{ github.repository == 'SalesforceCommerceCloud/pwa-kit' && failure() && github.ref == 'refs/heads/github-actions' && (matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo')
         uses: slackapi/slack-github-action@v1.23.0
         with:
           payload: |
@@ -238,3 +241,61 @@ jobs:
             }
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+  generated-windows:
+    strategy:
+      fail-fast: false
+      matrix:
+        template: [test-project, retail-react-app-demo, express-minimal-test-project, typescript-minimal-test-project]
+    runs-on: windows-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: 14
+
+      - name: Setup Windows Machine
+        uses: "./.github/actions/setup_windows"
+
+      - name: Generate ${{ matrix.template }} project
+        run: |-
+          set GENERATOR_PRESET=${{ matrix.template }}
+          node packages/pwa-kit-create-app/scripts/create-mobify-app-dev.js --outputDir generated-${{ matrix.template }}
+        env:
+          GENERATOR_PRESET: ${{ matrix.template }}
+        timeout-minutes: 5
+
+      - name: Run tests
+        if: matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo'
+        uses: "./.github/actions/runtests"
+        with:
+          cwd: generated-${{ matrix.template }}
+
+      - name: Smoke test scripts
+        if: matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo'
+        uses: "./.github/actions/smoketestscripts"
+        with:
+          dir: generated-${{ matrix.template }}
+
+      - name: Count Generated Project Dependencies
+        if: matrix.template == 'test-project' || matrix.template == 'retail-react-app-demo'
+        run: |-
+          MAX_PACKAGES="2260"
+          total=$(./scripts/count-dependencies.js generated-${{ matrix.template }})
+          echo "TOTAL_PACKAGES=${total}" >> $GITHUB_ENV
+
+          if [ "$total" -gt "$MAX_PACKAGES" ]; then
+              echo "Error: Found $TOTAL_PACKAGES installed packages (max $MAX_PACKAGES).";
+              exit 1;
+          else
+              echo "Found $TOTAL_PACKAGES installed packages (max $MAX_PACKAGES).";
+          fi
+        shell: bash
+      - name: Store Verdaccio logfile artifact
+        uses: actions/upload-artifact@v3
+        with:
+          path: packages/pwa-kit-create-app/local-npm-repo/verdaccio.log
+
+
